### ISSUE TITLE
About Experimental configuration and time-consuming

### ISSUE THREAD

**Issue by lk-uoser** [liu-yushan/TLogic#10]
1. Hello, what is the specific configuration of your experimental environment, GPU configuration, video memory size, how many blocks are used, and the time required for training on this basis?
2. Does data processing and reading require cpu memory?

**Comment by liu-yushan** [comment]
Hi,
1. All experiments were conducted on a Linux machine with 16 CPU cores and 32 GB RAM. No GPU configuration was used. Rule learning with 200 walks and exponentially weighted transition distribution for rule lengths {1, 2, 3} using 8 CPUs takes 180
sec for ICEWS14, while the application on the validation set takes 2000 sec.
2. Data is read and processed in RAM.
