### ISSUE TITLE
code_inquire

### ISSUE THREAD

**Issue by Junior-W** [liu-yushan/TLogic#11]
Dear Authors:
  I am interested in your Tlogic I would like to inquire about a code issue. There is a verbalize_walk funciton in your rule_application file.this function can display all paths that meet the rules. How can I use this verbalize_walk funciton  to obtain the final rule text.I hope to receive your reply.
![image](https://github.com/liu-yushan/TLogic/assets/68094392/cf405859-8357-4628-973a-d6a2572a2c3b)

**Comment by liu-yushan** [comment]
Hello, 
during rule application, we apply a *set* of rules to identify candidate objects and then calculate a score for each candidate. There is not a unique "final rule". 
If you want to print the walk during rule application, you can add `verbalize_walk` after line 94 in [apply.py](https://github.com/liu-yushan/TLogic/blob/main/mycode/apply.py). See cell 14 in the [demo](https://github.com/liu-yushan/TLogic/blob/main/mycode/demo.ipynb) for an example usage.
