### ISSUE TITLE
graph creation during the test time in inductive setting

### ISSUE THREAD

**Issue by navdeepkjohal** [liu-yushan/TLogic#8]
Dear Authors,

 

I am interested in your work TLogic and wish to use it as a baseline for our proposed model.

 

I have a question regarding the inductive setting (Table 3 arxiv version https://arxiv.org/pdf/2112.08025.pdf ), when you trained your model using ICEWS14 and test the model using ICEWS18, could you please tell us how did you ground your rules during the test time in inductive setting ?. Which out of the three settings: **(ICEWS14 train + ICEWS18 test)** or **(ICEWS18 test)** or **(ICEWS18 train + ICEWS18 test)** - did you use to create a KG in order to ground the rules during the test time ?
Please let us know.

 
Best
Navdeep

**Comment by TCcjx** [comment]
> Hi Navdeep,  你好，Navdeep，
> 
> or the inductive setting in Table 3, second row, we learned the rules on (ICEWS14 train) and tested on (ICEWS18 test), where the underlying KG for grounding the rules is (ICEWS18 train + ICEWS18 valid + ICEWS18 test) to test the transferability of the rules to another time frame. Note that not the complete ICEWS18 dataset is used but only the facts from the last 200 days before the query timestamp (as stated in the experimental details in the supplementary material) due to memory constraints. That means, it is the same test setting as in Table 1, column ICEWS18.或者如表 3 第二行所示的归纳设置，我们在（ICEWS14 训练集）上学习规则，并在（ICEWS18 测试集）上进行测试。其中，用于构建规则的底层知识图谱为（ICEWS18 训练集 + ICEWS18 验证集 + ICEWS18 测试集），以测试规则在不同时间段的迁移性。需要注意的是，由于内存限制，我们并未使用完整的 ICEWS18 数据集，而仅使用了查询时间戳前 200 天的数据（如补充材料中的实验细节所述）。这意味着，这与表 1 中 ICEWS18 列的测试设置相同。
Hello author,
Can I understand this as running python learn.py -d icews14 first, and then taking the generated rule file to run python apply.py -d icews18? However, the results I obtained are inconsistent with those reported in the paper. Could you please advise if there might be any incorrect settings on my end?
